### ISSUE TITLE
palagay ako image nito sa assets para sa about natin. salamat!!

### ISSUE THREAD

**Issue by aklra24** [John-Pio/PatingGames#3]
![aaron](https://github.com/John-Pio/PatingGames/assets/152205152/54946ac6-67ec-413a-aff4-d1e7e663548e)
![arvie](https://github.com/John-Pio/PatingGames/assets/152205152/0d7d5835-eaaf-498d-a2b5-48bed6560e29)
![geofrey](https://github.com/John-Pio/PatingGames/assets/152205152/8159ec30-52ee-4e25-9c24-ff911a37cfdc)
![mark](https://github.com/John-Pio/PatingGames/assets/152205152/ba1ef575-1a0c-495a-b951-40cde9157415)
![timmy](https://github.com/John-Pio/PatingGames/assets/152205152/b0d081ba-10c8-4b41-b30c-2bd24918a0d6)

**Comment by aklra24** [comment]
ayy aaron, lagay mo nalang pic mo. endi same size ee endi ko ma dl sa epbi mo

**Comment by arnplsrz** [comment]
oks, nalagay ko naa
